### PR TITLE
Add the ability to manually set DescriptorSet id

### PR DESCRIPTION
**Pull request by myname1111**
It was useful for my project, so it may be useful for someone else.

### CODE REVIEW

**Comment by jeronimosg** [comment]
Thanks for the PR! May I know how manually setting the descriptor ID is useful to you? (I'm looking for comments on the crate API).

In one of my initial iterations of the `DescriptorSet` there was the capability to set the ID, but I noticed I didn't use it and that I could introduce bind errors if the same ID was introduced without noticing.

**Comment by myname1111** [comment]
Hello. Yes, the reason why I needed to manually set the DescriptorSet id was because I wanted to implement linear algebra operations, and to do that I have written several functions, some with differing number of arguments.

For example I have a function called 'add_mat' which adds 2 matrices and stores the output in another matrix.
Similarly, I have another function called 'scale_mat' which takes 1 matrices, scale it an f32 scalar, and stores the output in another matrix.

As these function require different arguments I have made 3 bind groups.
```ignore
@group(0) @binding(0) var<storage, read>  in1: Vector;
@group(0) @binding(1) var<storage, read_write> out: Vector;

@group(1) @binding(0) var<storage, read>  in2: Vector;

@group(2) @binding(0) var<uniform> scalar: Scalar;
```

Bind group 0 contains the input/output matrices
Bind group 1 contains the second input matrix for the 'add_mat' function
Bind group 2 contains the scalar for the 'scale_mat' function

I assumed that you are able to not initialize these bind groups. If you cannot, feel free to correct me.
The reason that I needed to be able to manually set these bind groups is to have some of them uninitialized.

However, I have forgot to properly test my fork. It works for all the examples, and where you have all of the bind groups initialized. However, it doesn't work for seem to work for uninitialized bind groups, because my program crashes with this error

> The pipeline layout, associated with the current compute pipeline, contains a bind group layout at index {uninitialized bind group index} which is incompatible with the bind group layout associated with the bind group at {uninitialized bind group index}

I presume that this is the case as I have set the bind group layout, however I have not set the bind group itself. Therefore, conflict.

If this is not how I should implement my linear algebra operations, then tell me the correct way
If I am able to have unintialized bind groups, then tell me how

I am temporarily closing PR and will reopen once I have fixed the errors

**Comment by jeronimosg** [comment]
This very well suited for a new feature of the crate! Initially, I designed the `DescriptorSet` to ease the usage of bind groups, defining the layout and the actual bind within the same struct; so in the current state is not possible to create the layout and then do the binds. I'll have a look at this when I have more free time!

**Comment by myname1111** [comment]
Hello, I have decided to make the binding ids manually definable see https://github.com/UpsettingBoy/gpgpu-rs/pull/17 for more details

**Pull request closed without merging**
